// Form handling: collect inputs -> POST /api/recommend -> render result + 3D model.

const $ = (id) => document.getElementById(id);

function setText(id, value) {
  const el = $(id);
  if (el) el.textContent = (value === undefined || value === null || value === "") ? "-" : value;
}

async function getRecommendation() {
  const payload = {
    commodityName: $("commodityName").value.trim(),
    foodCategory: $("foodCategory").value,
    shelfLife: $("shelfLife").value,
    storageType: $("storageType").value,
    transport: $("transport").value,
    budget: $("budget").value,
    productWeight: $("productWeight").value,
    packetWeight: $("packetWeight").value,
    packetUnit: $("packetUnit").value,
  };

  const status = $("statusMsg");
  const btn = $("submitBtn");

  if (!payload.commodityName || !payload.foodCategory || !payload.shelfLife ||
      !payload.productWeight || !payload.packetWeight) {
    status.textContent = "⚠️ Please fill commodity name, category, shelf life, product weight and packet weight.";
    return;
  }

  const totalKg = parseFloat(payload.productWeight);
  const packetKg = parseFloat(payload.packetWeight) / (payload.packetUnit === "g" ? 1000 : 1);
  if (!(totalKg > 0) || !(packetKg > 0) || totalKg > 10000000) {
    status.textContent = "⚠️ Enter a realistic product weight (kg) and packet weight.";
    return;
  }
  if (packetKg > totalKg) {
    status.textContent = "⚠️ Packet weight cannot be more than the total product weight.";
    return;
  }

  btn.disabled = true;
  status.textContent = "⏳ Analysing commodity and predicting properties...";

  try {
    const res = await fetch("/api/recommend", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new Error("Server error " + res.status);
    const r = await res.json();
    renderResult(r, payload);
    status.textContent = "";
  } catch (err) {
    status.textContent = "❌ Could not get a recommendation: " + err.message;
  } finally {
    btn.disabled = false;
  }
}

function renderResult(r, payload) {
  $("resultCard").style.display = "block";

  const isAI = r.source === "gemini_ai" || r.source === "openrouter_ai";
  const provider = r.source === "openrouter_ai" ? "OpenRouter" : "Gemini";
  $("sourceBadge").textContent = isAI
    ? "🤖 Generated by AI (" + provider + (r.ai_model ? ": " + r.ai_model : "") + ")"
    : "📴 Offline Rule Engine";

  const p = r.predicted_properties || {};
  setText("pMoisture", p.moisture_pct);
  setText("pFat", p.fat_pct);
  setText("pPh", p.ph);
  setText("pResp", p.respiration_rate);
  setText("pTemp", p.storage_temp_c);
  setText("pRh", p.relative_humidity_pct);

  setText("rMaterial", r.material);
  setText("rReasoning", r.reasoning);
  setText("rOtr", r.otr_value);
  setText("rWvtr", r.wvtr_value);
  setText("rThickness", r.film_thickness_microns);
  setText("rSeal", r.sealability);
  setText("rGasPerm", r.gas_permeability);
  setText("rMechStrength", r.mechanical_strength);
  setText("rMapSuit", r.map_suitability);
  setText("rMapGas", r.map_gas_composition);
  setText("rGas", r.gas_filler);
  setText("rSustainable", r.sustainable_option);
  setText("rShelfLife", r.shelf_life_prediction_days);
  setText("rCost", r.cost_estimate);
  setText("rQr", r.qr_traceability_note);

  // Packets from the batch (client-side maths)
  const totalG = parseFloat(payload.productWeight) * 1000;
  const packetG = parseFloat(payload.packetWeight) * (payload.packetUnit === "kg" ? 1000 : 1);
  setText("rPackets", packetG > 0 ? Math.ceil(totalG / packetG) + " packets of " + payload.packetWeight + " " + payload.packetUnit : "-");

  // 3D model(s): "layers" is 1 entry for a normal pack, 2 for a case/bulk pack that
  // needs an inner liner + an outer box/bulk bag (viewer3d.js exposes window.loadPackagingLayers).
  const layers = (r.layers && r.layers.length) ? r.layers
    : [{ shape: r.packaging_shape, label: r.packaging_shape, model_url: r.model_url }];
  renderLayerTabs(layers, payload);
  showLayer(layers, 0, payload);

  $("resultCard").scrollIntoView({ behavior: "smooth" });
}

function showLayer(layers, index, payload) {
  const layer = layers[index] || {};
  const cap = $("modelCaption");
  if (cap) {
    const countTxt = layers.length > 1 ? "Layer " + (index + 1) + " of " + layers.length + " · " : "";
    cap.textContent = "🖱️ Drag to rotate · " + countTxt + (layer.label || layer.shape) +
      " for " + payload.packetWeight + " " + payload.packetUnit + " packs" +
      (layer.model_url ? "" : " (no 3D file for this pack type yet - showing a placeholder shape)");
  }
  if (window.loadPackagingModel) {
    window.loadPackagingModel(layer.model_url, layer.shape);
  } else {
    window.__pendingModel = [layer.model_url, layer.shape];   // viewer module not ready yet
  }
}

function renderLayerTabs(layers, payload) {
  const box = $("layerTabs");
  if (!box) return;
  if (layers.length <= 1) {
    box.style.display = "none";
    box.innerHTML = "";
    return;
  }
  box.style.display = "flex";
  box.innerHTML = layers.map((l, i) =>
    '<button type="button" class="layer-tab' + (i === 0 ? " active" : "") + '" data-i="' + i + '">' +
    (i + 1) + ". " + (l.label || l.shape) + "</button>"
  ).join("");
  box.querySelectorAll(".layer-tab").forEach((btn) => {
    btn.addEventListener("click", () => {
      box.querySelectorAll(".layer-tab").forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      showLayer(layers, parseInt(btn.dataset.i, 10), payload);
    });
  });
}
